CREATE DATABASE BTECH_3A_133

CREATE TABLE DEPOSIT(
	ACTNO INT,
	CNAME VARCHAR(50),
	BNAME VARCHAR(50),
	ADATE DATETIME,
	AMOUNT DECIMAL(8,2)
);


CREATE TABLE BRANCH(
	BNAME VARCHAR(50),
	CITY VARCHAR(50)
);

CREATE TABLE CUSTOMERS(
	CNAME VARCHAR(50),
	CITY VARCHAR(50)
);

CREATE TABLE BORROW(
	LOANNO INT,
	CNAME VARCHAR(50),
	BNAME VARCHAR(50),
	AMOUNT DECIMAL(8,2)
);

INSERT INTO DEPOSIT VALUES (109, 'MINNU', 'POWANI', '1995-8-10', 7000)

SELECT * FROM DEPOSIT

INSERT INTO BRANCH VALUES ('POWAI', 'BOMBAY')

SELECT * FROM BRANCH

INSERT INTO CUSTOMERS VALUES ('NAREN', 'BOMBAY')

SELECT * FROM CUSTOMERS

INSERT INTO BORROW VALUES (201, 'ANIL', 'VRCE', 1000)
INSERT INTO BORROW VALUES (206, 'MEHUL', 'AJNI', 5000)
INSERT INTO BORROW VALUES (311, 'SUNIL', 'DHARAMPETH', 3000)
INSERT INTO BORROW VALUES (321, 'MADHURI', 'ANDHERI', 2000)
INSERT INTO BORROW VALUES (375, 'PRAMOD', 'VIRAR', 8000)
INSERT INTO BORROW VALUES (481, 'KRANTI', 'NEHRU PLACE', 3000)

SELECT * FROM BORROW